#import <Foundation/Foundation.h>
#import <CoreText/CoreText.h>

@interface ZynthIconsFontRegistrar : NSObject
@end

@implementation ZynthIconsFontRegistrar
@end

__attribute__((constructor)) static void ZynthIconsRegisterFonts(void) {
  NSBundle *classBundle = [NSBundle bundleForClass:[ZynthIconsFontRegistrar class]];
  
  // Try to find the resource bundle generated by CocoaPods
  NSURL *resourceBundleURL = [classBundle URLForResource:@"ZynthIcons" withExtension:@"bundle"];
  NSBundle *fontBundle = resourceBundleURL ? [NSBundle bundleWithURL:resourceBundleURL] : classBundle;
  
  NSLog(@"[ZynthIcons] Registering fonts from bundle: %@", fontBundle.bundlePath);
  
  // When using resource_bundles, files are usually at the root of the .bundle
  NSArray<NSURL *> *fonts = [fontBundle URLsForResourcesWithExtension:@"ttf" subdirectory:nil];
  
  // Fallback: check 'Fonts' subdirectory if we are in a flattened structure
  if (fonts.count == 0) {
    fonts = [fontBundle URLsForResourcesWithExtension:@"ttf" subdirectory:@"Fonts"];
  }
  
  NSLog(@"[ZynthIcons] Found %lu fonts to register.", (unsigned long)fonts.count);
  
  for (NSURL *url in fonts) {
    CFErrorRef error = NULL;
    if (!CTFontManagerRegisterFontsForURL((__bridge CFURLRef)url, kCTFontManagerScopeProcess, &error)) {
      NSError *nsError = (__bridge NSError *)error;
      NSLog(@"[ZynthIcons] Failed to register font at %@: %@", url.lastPathComponent, nsError.localizedDescription);
    } else {
      NSLog(@"[ZynthIcons] Successfully registered font: %@", url.lastPathComponent);
    }
  }
}
