// AUTO-GENERATED by packages/zynth-icons/scripts/generate.ts. Do not edit.
type WebFontSources = Record<string, string>;

const sources: WebFontSources = {
  ZynthIconsAI: new URL("../assets/fonts/ZynthIconsAI.ttf", import.meta.url).toString(),
  ZynthIconsBI: new URL("../assets/fonts/ZynthIconsBI.ttf", import.meta.url).toString(),
  ZynthIconsBS: new URL("../assets/fonts/ZynthIconsBS.ttf", import.meta.url).toString(),
  ZynthIconsCG: new URL("../assets/fonts/ZynthIconsCG.ttf", import.meta.url).toString(),
  ZynthIconsFA: new URL("../assets/fonts/ZynthIconsFA.ttf", import.meta.url).toString(),
  ZynthIconsFI: new URL("../assets/fonts/ZynthIconsFI.ttf", import.meta.url).toString(),
  ZynthIconsHI: new URL("../assets/fonts/ZynthIconsHI.ttf", import.meta.url).toString(),
  ZynthIconsIM: new URL("../assets/fonts/ZynthIconsIM.ttf", import.meta.url).toString(),
  ZynthIconsIO: new URL("../assets/fonts/ZynthIconsIO.ttf", import.meta.url).toString(),
  ZynthIconsOC: new URL("../assets/fonts/ZynthIconsOC.ttf", import.meta.url).toString(),
  ZynthIconsRI: new URL("../assets/fonts/ZynthIconsRI.ttf", import.meta.url).toString(),
  ZynthIconsSI: new URL("../assets/fonts/ZynthIconsSI.ttf", import.meta.url).toString(),
  ZynthIconsTB: new URL("../assets/fonts/ZynthIconsTB.ttf", import.meta.url).toString(),
  ZynthIconsTI: new URL("../assets/fonts/ZynthIconsTI.ttf", import.meta.url).toString(),
  ZynthIconsVS: new URL("../assets/fonts/ZynthIconsVS.ttf", import.meta.url).toString(),
  ZynthIconsWI: new URL("../assets/fonts/ZynthIconsWI.ttf", import.meta.url).toString(),
};

const globalObj =
  typeof globalThis !== "undefined"
    ? (globalThis as any)
    : (window as any);

const existing = globalObj.__zynth_web_font_sources;
if (existing && typeof existing === "object") {
  Object.assign(existing, sources);
} else {
  globalObj.__zynth_web_font_sources = sources;
}
