// AUTO-GENERATED by packages/zynth-icons/scripts/generate.ts. Do not edit.
export const runtimeGlyphMap: Record<string, string> = {
  "BiRegularDotsVertical": "",
  "IoArrowBackOutline": "",
  "RiArrowsArrowLeftLine": "",
  "RiArrowsArrowLeftSLine": "",
  "RiArrowsArrowRightSLine": "",
  "RiArrowsArrowUpSLine": "",
  "RiDevelopmentTerminalBoxLine": "",
  "RiDocumentFileCopyLine": "",
  "RiSystemAlertLine": "",
  "RiSystemCloseLine": "",
  "RiSystemDeleteBin2Line": "",
  "RiSystemEyeCloseLine": "",
  "RiSystemEyeLine": "",
  "RiSystemRefreshLine": "",
  "RiSystemSearchLine": "",
  "RiUserFacesUserLine": ""
};
export const runtimeFontFamily = "ZynthRuntime";
export const runtimeFontFile = "ZynthRuntime.ttf";
