// AUTO-GENERATED by packages/zynth-icons/scripts/generate.ts. Do not edit.
export const runtimeGlyphMap: Record<string, string> = {
  "BsArrowLeftShort": "",
  "BsThreeDotsVertical": ""
};
export const runtimeFontFamily = "ZynthRuntimeIcons";
export const runtimeFontFile = "ZynthRuntimeIcons.ttf";
