// AUTO-GENERATED by packages/zynth-icons/scripts/generate.ts. Do not edit.
package dev.zynth.icons;

import android.content.ContentProvider;
import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.net.Uri;
import android.util.Log;

import java.lang.reflect.Method;

public final class ZynthIconsInitProvider extends ContentProvider {
  private static final String TAG = "ZynthIconsInit";
  private static final String[] FONT_FAMILIES = new String[] {
    "ZynthIconsAI",
    "ZynthIconsBI",
    "ZynthIconsBS",
    "ZynthIconsCG",
    "ZynthIconsFA",
    "ZynthIconsFI",
    "ZynthIconsHI",
    "ZynthIconsIM",
    "ZynthIconsIO",
    "ZynthIconsOC",
    "ZynthIconsRI",
    "ZynthIconsSI",
    "ZynthIconsTB",
    "ZynthIconsTI",
    "ZynthIconsVS",
    "ZynthIconsWI"
  };

  @Override
  public boolean onCreate() {
    Context context = getContext();
    if (context == null) {
      return true;
    }

    try {
      Class<?> registryClass = Class.forName("com.zynth.kit.runtime.FontRegistry");
      Object registry = registryClass.getField("INSTANCE").get(null);
      Method initialize = registryClass.getMethod("initialize", Context.class);
      Method loadFont = registryClass.getMethod("loadFont", String.class, String.class);

      initialize.invoke(registry, context.getApplicationContext());

      for (String family : FONT_FAMILIES) {
        loadFont.invoke(registry, family, family + ".ttf");
      }
    } catch (Throwable error) {
      Log.w(TAG, "Failed to pre-register icon fonts", error);
    }

    return true;
  }

  @Override
  public Cursor query(Uri uri, String[] projection, String selection, String[] selectionArgs, String sortOrder) {
    return null;
  }

  @Override
  public String getType(Uri uri) {
    return null;
  }

  @Override
  public Uri insert(Uri uri, ContentValues values) {
    return null;
  }

  @Override
  public int delete(Uri uri, String selection, String[] selectionArgs) {
    return 0;
  }

  @Override
  public int update(Uri uri, ContentValues values, String selection, String[] selectionArgs) {
    return 0;
  }
}
