// AUTO-GENERATED by packages/rune-icons/scripts/generate.ts. Do not edit.
export const runtimeGlyphMap: Record<string, string> = {
  "BsArrowLeftShort": "",
  "BsThreeDotsVertical": ""
};
export const runtimeFontFamily = "RuneRuntimeIcons";
export const runtimeFontFile = "RuneRuntimeIcons.ttf";
