// AUTO-GENERATED by packages/rune-icons/scripts/generate.ts. Do not edit.
type WebFontSources = Record<string, string>;

const sources: WebFontSources = {
  RuneIconsAI: new URL("../assets/fonts/RuneIconsAI.ttf", import.meta.url).toString(),
  RuneIconsBI: new URL("../assets/fonts/RuneIconsBI.ttf", import.meta.url).toString(),
  RuneIconsBS: new URL("../assets/fonts/RuneIconsBS.ttf", import.meta.url).toString(),
  RuneIconsCG: new URL("../assets/fonts/RuneIconsCG.ttf", import.meta.url).toString(),
  RuneIconsFA: new URL("../assets/fonts/RuneIconsFA.ttf", import.meta.url).toString(),
  RuneIconsFI: new URL("../assets/fonts/RuneIconsFI.ttf", import.meta.url).toString(),
  RuneIconsHI: new URL("../assets/fonts/RuneIconsHI.ttf", import.meta.url).toString(),
  RuneIconsIM: new URL("../assets/fonts/RuneIconsIM.ttf", import.meta.url).toString(),
  RuneIconsIO: new URL("../assets/fonts/RuneIconsIO.ttf", import.meta.url).toString(),
  RuneIconsOC: new URL("../assets/fonts/RuneIconsOC.ttf", import.meta.url).toString(),
  RuneIconsRI: new URL("../assets/fonts/RuneIconsRI.ttf", import.meta.url).toString(),
  RuneIconsSI: new URL("../assets/fonts/RuneIconsSI.ttf", import.meta.url).toString(),
  RuneIconsTB: new URL("../assets/fonts/RuneIconsTB.ttf", import.meta.url).toString(),
  RuneIconsTI: new URL("../assets/fonts/RuneIconsTI.ttf", import.meta.url).toString(),
  RuneIconsVS: new URL("../assets/fonts/RuneIconsVS.ttf", import.meta.url).toString(),
  RuneIconsWI: new URL("../assets/fonts/RuneIconsWI.ttf", import.meta.url).toString(),
};

const globalObj =
  typeof globalThis !== "undefined"
    ? (globalThis as any)
    : (window as any);

const existing = globalObj.__rune_web_font_sources;
if (existing && typeof existing === "object") {
  Object.assign(existing, sources);
} else {
  globalObj.__rune_web_font_sources = sources;
}
